{
 "title": "Pizza Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "PIZZAS SOLD PER MINUTE",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(pizzas_sold_total{source=\"jwt-pizza-service-dev\"}[1m])",
     "legendFormat": "Pizzas Sold Per Minute"
    }
   ]
  },
  {
   "title": "REVENUE PER MINUTE",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(pizza_revenue_total_USD{source=\"jwt-pizza-service-dev\"}[1m])",
     "legendFormat": "Revenue"
    }
   ]
  },
  {
   "title": "PIZZA CREATION FAILURE",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "pizza_creation_failures_total{source=\"jwt-pizza-service-dev\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "PIZZA CREATION LATENCY",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "pizza_creation_latency_ms_milliseconds{source=\"jwt-pizza-service-dev\"}",
     "legendFormat": "Latency of creation"
    }
   ]
  },
  {
   "title": "CPU AND MEMORY",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cpu_usage_percent{source=\"jwt-pizza-service-dev\"}",
     "legendFormat": "CPU Percentage in Use"
    },
    {
     "expr": "memory_usage_percent{source=\"jwt-pizza-service-dev\"}",
     "legendFormat": "Memory Percentage in Use"
    }
   ]
  },
  {
   "title": "Active User Count",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "active_users_last_5min{source=\"jwt-pizza-service-dev\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP REQUEST BY METHOD PER MINUTE",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "sum by (method) (rate(http_requests_by_method_total{source=\"jwt-pizza-service-dev\"}[1m])) * 60",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Successful vs Failed Login Attempts per Minute",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(auth_success_total{source=\"jwt-pizza-service-dev\"}[1m])",
     "legendFormat": "Successful Attempts"
    },
    {
     "expr": "irate(auth_failure_total{source=\"jwt-pizza-service-dev\"}[1m])",
     "legendFormat": "Failed Attempts"
    }
   ]
  },
  {
   "title": "PIZZA-SERVICE HTTP Requests",
   "type": "timeseries",
   "description": "Observes the total requests from the app as well as the request by method per minute.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "http_requests_total{source=\"jwt-pizza-service-dev\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "PIZZA-SERVICE HTTP REQUEST LATENCY",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "targets": [
    {
     "expr": "avg by(method) (http_avg_latency_ms_milliseconds{source=\"jwt-pizza-service-dev\"})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}